# -*- coding: utf-8 -*-
"""Data cleaning_Books.jpynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JX3WuvwVI9E9CQ_zz9iXWW15Zvqp02Yd
"""

import pandas as pd
import numpy as np
from functools import reduce

book=pd.read_csv("/content/drive/MyDrive/BL-Flickr-Images-Book.csv")
print(book.head())

book.shape

for col in book:
  print(col)

to_drop=["Edition Statement",
         'Corporate Author',
         'Corporate Contributors',
         'Former owner',
         'Engraver',
         'Contributors',
         'Issuance type',
         'Shelfmarks']
book.drop(to_drop,inplace=True,axis=1)
book.head()

for col in book:
  print(col)

book.set_index('Identifier',inplace=True)
book.head()

book['Date of Publication'].head(25)

unwanted_characters=['[',',','-']

def clean_dates(item):
 dop=str(item.loc['Date of Publication'])

 if dop=='nan'or dop[0]=='[':
  return np.NaN

 for character in unwanted_characters:
  if character in dop:
    character_index=dop.find(character)
    dop=dop[:character_index]
    return dop

book['Date of Publication']=book.apply(clean_dates,axis=1)

book['Date of Publication'].head(25)

def clean_Title(Title):

 if Title=='nan':
  return'NaN'

 if Title[0]=='[':
  Title=Title[1:Title.find(']')]

 if 'by' in Title:
  Title=Title[:Title.find('by')]
 elif 'By' in Title:
  Title=Title[:Title.find('By')]

 if'['in Title:
  Title=Title[:Title.find('[')]

 Title=Title[:-2]

 Title=list(map(str.capitalize,Title.split()))
 return''.join(Title)

book['Title']=book['Title'].apply(clean_Title)
book.head()

